[package]
name = "project-euler-rust"
version = "0.1.0"
authors = ["asampley <alex.sampley@gmail.ca>"]
edition = "2021"

[dependencies]
automod = "1.0.12"
duplicate = "1.0.0"
itertools = "0.11.0"
num = "0.4.0"
num_enum = "0.6.1"
